### ISSUE TITLE
Dash lags when using i racing online, but is fine in offline (test) mode

### ISSUE THREAD

**Issue by dano555** [SHWotever/SimHub#506]
I've just setup sim hub to use with the PSE DDU, it works fine and all the changes are instant on the dash when using iracing in offline mode, but when i go to an online session or race, there is like a 3 second delay between changing gear and it updating on the dash, so sometimes its 2 gears behind what the car is actually in.

Anyone had this before and know how to fix it?

I've tried changing the setting in dash studio to web engine = slow but that didn't make any difference.....

The dash I’ve been using is the PSE template  that comes with the hardware (bosch style)

**Comment by dano555** [comment]
[SimHub.log](https://github.com/SHWotever/SimHub/files/4303389/SimHub.log)

**Comment by SHWotever** [comment]
Hi ! Unfortunately the log shows nothing anormal, could you confirm it was logged during the online session ? 

As a first step I would try to set Simhub as high priority to ensure it's not a CPU bottleneck happening, you can set simhub priority here : 
![image](https://user-images.githubusercontent.com/2207331/76165608-b7fc4100-6158-11ea-88cd-0b038f662779.png)

Nicolas

**Comment by dano555** [comment]
[SimHub.log](https://github.com/SHWotever/SimHub/files/4331502/SimHub.log)
I cant remember if that log file was for an online session. See attached a new file where the last few sessions were definitely online.

**Comment by SHWotever** [comment]
Thanks for the logs, it indeed shows latency issues while "talking" with the usbd480. Have you tried to set simhub as high priority like I suggested ? I see in the log that it's currently disabled. Since it happens only online I still think about a CPU bottleneck. 
Even if CPU remains my first guess due to the fact that it happens only online It could be interresting to reinstall display drivers and test a another usb cable, I see that you are using a simucube base and direct drive is known to easily cause such issues (due to EMI) which is most of the time solved with a better insulated USB cable. (Also avoid usb hubs for the display as it can also cause issues.

Let me know,
Nicolas

**Comment by dano555** [comment]
Hi Nicolas

I’ve tried the CPU priority and still get the lag. The newest development is that maybe after 30 mins of running, SimHub crashes, so I re-launch SimHub, open I racing then it works as it should (even online).

But once I restart sim hub after that it goes back to having the delay, which is quite strange.

		
Daniel O'Brien
Managing Director, Willow Hire
01582 840045  | 07793159196  | dan@willowhire.com  | www.willowhire.com | Hill and Coles farm, london rd, St Albans, Herts, AL3 8HA

**Comment by SHWotever** [comment]
Thanks for the information, so cpu is not the bottleneck, so we need to to focus on display itself, here some additional clues : 
- The usbd480 drivers uninstall/reinstall and new usb cable didn't help ? I know that the usbd480 library provided by the manufacturer is not 100% stable when there are communication issues, that could explain the crash. 
- Are you using a usb hub ? They often cause issues, moreover on high bandwidth devices like the usbd480
- Have you tried to keep the screen away from the wheel to ensure emi wasn't part of the problem ?

**Comment by dano555** [comment]
HI, I've just tried the new usb cables and putting the dash away from the wheel, which didn't cure it. I didnt use a hub as the cable run is short enough to get to the PC directly. 
I'll try uninstalling the drivers next.

The only time it seems to work is after simhub crashes and re-opens. It has now started the delay in offline mode also now.

**Comment by dano555** [comment]
I’ve uninstalled and reinstalled both the drivers and the SimHub software, but the delay is still there. I’ve also installed z1, which runs fine with no delay. (But isn’t as good as SimHub when it works correctly)

**Comment by dano555** [comment]
Did you have any other ideas for me to try?

**Comment by SHWotever** [comment]
Hi ! Unfortunately no additional ideas yet, I know that z1 sends 16bits colours while I use 24bits which uses more usb bandwidth. The logs were clearly showing usb communication issues which matches your issues, but at this point the delay occurs in the usbd480 communication library provided by the manufacturer and I don't have hand on it. Usually when this happens it has always been a usb issue (drivers, bad cable, usb hub ...) And the fact that z1 was working wasn't a meaningful clue (due to the 24bits/16bits difference) . I will try to take contact with the screen manufacturer (lcdinfo) to see if I can get some additional clues.

**Comment by SHWotever** [comment]
Hi ! In the latest version, you will find a new setting allowing to cap FPS this should reproduce the z1 behaviour (witch is sending at a 50fps rate)
![image](https://user-images.githubusercontent.com/2207331/79896777-0fa0f400-8409-11ea-9ba2-76df18da9e94.png)

Let me know if it helped,
Nicolas

**Comment by dano555** [comment]
Afraid that's not made any difference.
Dropped down to 30fps and tried a few games including acc and dirt rally 2. but still that 3 second delay.

**Comment by dano555** [comment]
[SimHub.log](https://github.com/SHWotever/SimHub/files/4532960/SimHub.log)

**Comment by SHWotever** [comment]
I'm clueless :( . Do you have a window 10 computer to test it ? I don't test any more windows 7 as it has officially passed away in January. Maybe it's related to the OS

**Comment by gurlinol** [comment]
[SimHub.log](https://github.com/SHWotever/SimHub/files/5070910/SimHub.log)
@dano555 hey dude, did you solve the issue? If so, what did you do?
@SHWotever Hi there; I have the exact same problem. I read carefully this chain and followed all your suggestion. Attached Log. Yet, SimHub lag for 2-3 secs in any game (ACC, Assetto Corsa, F1 2020, iRacing) offline. Didn't bother to go online. I'm on PC (of course) Win 10, USBD480 in a Pololo Instruments dash-screen. Z1 and DashPanel worked fine. No issues. But we all agree SimHub "should be better"
Any guidelines for me? - cheers.
P.S. I also noticed that, when I load a dash template into my screen, it does not load fast. It also lags for some seconds.

**Comment by SHWotever** [comment]
Hi !
I've found a repro case, and I've been able to do a fix, this should solve this problem or similar. However I maintain the windows 7 part, it's not supported anymore by microsoft, so i've not made any particular tests on this OS.

Nicolas

**Comment by simutec** [comment]
@SHWotever -

Hi Nicolas, sorry to tag onto this thread. I have however stumbled across this and am having the exact same issue with a 2 second refresh lag.
The hardware spec:
USB 3.0 to device
Integrated USB hub on PCB
Arduino Nano on PCB
18 RGB LED's
USBD480

I have tried all the following:
Various cables
Connecting directly to USBD480 (bypassing USB hub and Arduino)
Running the licensed version of SimHub
Changing the refresh rate limit
Disabling LED's
Less dynamic content on the display

Despite the above attempts, the lag is noticeable on the "Current Lap Time" timer.
Weirdly I have however found a strange workaround... once I have clicked "Drive" on AC, I then click the SimHub application on another window to make this the uppermost app and the display runs without any lag whatsoever.

I am happy to send you a prototype dash for you to test with.

Calum
